version: '3.7'

services:
  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['./:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    ports: ['8000:80']
    volumes: ['./:/var/www/symfony:cached']

networks:
  default:
    name: scrapers-network
