version: '3.7'
services:
  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['./symfony/:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    ports: ['8080:80']
    volumes: ['./symfony/:/var/www/symfony:cached']
